version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'p@ssword'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
  app:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    volumes:
      - .:/cfj_election_front
    ports:
      - '3000:3000'
      - '8000:8000'
    depends_on:
      - db
